---
- name: Create Instances EC2
  hosts: localhost
  connection: local
  ec2:
    key_name: mykey
    group: "{{ group_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    wait_timeout: 500
    count: "{{ instance_count }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 10
          delete_on_termination: true
    monitoring: yes
    vpc_subnet_id: "{{ vpc_subnet }}"
    assign_public_ip: yes
  when: Instance_auto_deploy.enabled == true

#- name: Terminate instances
#  hosts: localhost
#  connection: local
#  tasks:
#    - name: Terminate instances that were previously launched
#      ec2:
#        state: 'absent'
#        instance_ids: '{{ ec2.instance_ids }}'
#  when: terminate_all == true and Instance_auto_deploy.enabled == true
