---
- name: Run "apt-get update"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Prometheus Node Exporter install
  package: pkg={{ item }} state=installed 
  with_items:
    - prometheus-node-exporter
  when: enable_node_exporter | default(true)

- name: Nginx install
  package: pkg={{ item }} state=installed 
  with_items:
    - nginx
    - nginx-extras
  when: enable_nginx | default(true)

- name: Docker Install
  package: pkg={{ item }} state=installed 
  with_items:
    - docker.io
    - docker-compose

- name: Additional App install
  package: pkg={{ item }} state=installed 
  with_items:
    - vim
    - wget
    - curl
    - git

- name: Directory for docker-compose servies data creation
  file:
    path: "/opt/{{ item }}"
    state: directory
  with_items:
    - data/cadvisor

- name: Docker-compose config installation
  copy: src=docker-compose/docker-compose.yaml dest=/opt/config/docker-compose.yaml

- name: Docker-compose starting
  docker_compose:
    project_src: /opt/config/
    build: no

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  when: enable_nginx | default(true)
